language: python
env:
    - MNEMOSYNE_SETTINGS='settings_test.py'
python:
  - "2.7"
before_install:
  - pip install coveralls --use-mirrors
install:
  - python setup.py install
script: nosetests -v --with-coverage --cover-erase --cover-package=mnemosyne
after_success:
  - coveralls
notifications:
  hipchat: 11e2176ebb4b7372ee0d1fbc8abf4d@Github
